### ISSUE TITLE
Error while attempting to login using the default API name 

### ISSUE THREAD

**Issue by marc-aurele-besner** [Sindri-Labs/sindri-js#109]
## Error while attempting to login using the default API name error is generated

Trying to login using the default API name, it return an error if the hostname is pretty long

<img width="897" alt="image" src="https://github.com/Sindri-Labs/sindri-js/assets/82244926/e0c56c5e-f5dd-4503-9973-81c707adfe24">

The [hostname](https://github.com/Sindri-Labs/sindri-js/blob/8beb80db55ebc80cdf07e3558c9a1dcb7b21b045/src/cli/login.ts#L62) should be trim

**Comment by sangaline** [comment]
Thanks for reporting and for submitting your #110 PR! That has been merged now, and I also added client-side length validation in #111. Both changes are available in the latest `v0.0.1-alpha.48` release. Please let us know if you run into any additional issues, and thanks again for contributing.
