### ISSUE TITLE
Login Forbidden Error

### ISSUE THREAD

**Issue by anirudhaCodes** [Sindri-Labs/sindri-js#48]
### **Description:**
While attempting to log in using sindri, I encountered a "Forbidden" error with a 403 status code. This issue prevents successful authentication despite providing correct credentials.

```
node@docker-desktop:/sindri$ sindri -d login -u http://host.docker.internal login
[05:49:58.931] DEBUG: Set log level to "trace".
[05:49:58.952] DEBUG: Config file "/home/node/.config/sindri/sindri.conf.json" does not exist, initializing default config.
? Username: test
? Password: ****
? New API Key Name: docker-desktop-sdk
[05:51:12.565] FATAL: An irrecoverable error occurred.
[05:51:12.565] ERROR: Forbidden
    err: {
      "type": "ApiError",
      "message": "Forbidden",
      "stack":
          ApiError: Forbidden
              at catchErrorCodes (/sindri/dist/cli/index.js:453:11)
              at /sindri/dist/cli/index.js:502:9
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "url": "http://host.docker.internal/api/token/pair",
      "status": 403,
      "statusText": "connecting to host.docker.internal:80: connecting to 127.0.0.1:80: dial tcp 127.0.0.1:80: connectex: No connection could be made because the target machine actively refused it.",
      "body": "connecting to host.docker.internal:80: connecting to 127.0.0.1:80: dial tcp 127.0.0.1:80: connectex: No connection could be made because the target machine actively refused it.",
      "request": {
        "method": "POST",
        "url": "/api/token/pair",
        "body": {
          "username": "test",
          "password": "||||"
        },
        "mediaType": "application/json"
      },
      "name": "ApiError"
    }
```

### **Steps to Reproduce:**
```
docker compose up
docker compose exec sindri-js bash
sindri -d login -u http://host.docker.internal login
```

Request:
Kindly assist in troubleshooting this issue to enable successful authentication via sindri using docker.
@sangaline 

Thank you

**Comment by sangaline** [comment]
@anirudhaCodes Using the `host.docker.internal` host assumes that you have a local version of the Sindri API running on your machine. The API itself is not part of this open source client, and that sort of usage is intended for Sindri developers to work on integrating with new API features before they're publicly released. I can update the README to make this more clear.

Do you have an account at [Sindri](https://sindri.app)? If so, you can leave off the `-u` argument and it will automatically connect to the production service. If you would just like to use the CLI client rather than actively modify/develop it, then you can also run `npx sindri@latest login` without needing to clone the repo, run docker, etc.

We also have a [Getting Started with Sindri CLI](https://sindri.app/docs/getting-started/cli/) that walks through how to use the client.

**Comment by anirudhaCodes** [comment]
I currently do not have a Sindri account. To acquire one, I assume I need to submit a demo request, correct? My intention was to integrate the Sindri prove command into the CLI, hence I began setting up the repository in my local environment. What would be the recommended steps for me to move forward with this integration?

**Comment by sangaline** [comment]
Yes, you'll need to submit a demo request to get set up. There's a link on the [Sindri Homepage](https://sindri.app/) to do so. We have plans to make the CLI more useful without an account, but it's currently required for anything beyond scaffolding out a new circuit project.

Also note that there's an existing PR for the prove command: #40. It's great that you want to contribute to the project, but I should mention that it's still in very early stages and code is going to shift around quite a bit in the near future. In particular, we're in the process of adding an SDK, and the CLI portion is going to be refactored to use the SDK. My recommendation would be to wait until we hit our first non-alpha release before submitting any PRs, the codebase should be more stable at that point and less of a moving target. Any feedback on the CLI or feature requests would also be very much appreciated in the meantime.

**Comment by anirudhaCodes** [comment]
I did demo request like 5 days. but didn't got any reply
